import subprocess
import sys
import os

def run_gui():
    """Run the GUI to create the processing element and save to a JSON file."""
    print("Launching APEX version 1.0 ...")
    subprocess.run(["python3", "pe-creator.py"])  # Assuming pe-creator.py is your frontend GUI

def generate_verilog(json_file):
    """Run the Verilog generator with the provided JSON file."""
    if not os.path.exists(json_file):
        print(f"Error: JSON file {json_file} does not exist!")
        return
    print(f"Generating Verilog from {json_file}...")
    subprocess.run(["./apex_vgen", json_file])  # Assuming 'pec' is the compiled Verilog generator

def main():
    """Main function to run the complete process."""
    # Run the GUI to create the JSON file
    run_gui()

    # Ask for the path of the JSON file generated by the GUI
    #json_file = input("Enter the path to the generated JSON file: ")
    json_file = 'apex.log'
    with open(json_file, 'r') as json_file:
        json_file = json_file.read() + '.json'

    # Generate the Verilog from the JSON
    generate_verilog(json_file)
    print("Verilog generation completed.")

if __name__ == "__main__":
    main()
